### ISSUE TITLE
Missing References

### ISSUE THREAD

**Issue by Paragrimm** [JellyBitz/xBot-WinForms#1]
Hey, I'm trying to build and test your bot, but unfortunately there are several references missing.

- AutoUpdater.NET
- DevIL.NET2

Could you please help me out with that?

**Comment by JellyBitz** [comment]
Remove it and try to add the missing DLL references again.
https://github.com/JellyBitz/xBot-WinForms/tree/master/xBot/bin/Release

**Comment by Paragrimm** [comment]
Thanks, I can build it now, but I can't use it. If I publish and install xBot, it crashes immediatly without an error. If I start it directly from Visual Studio, I get the following error:

```
Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei xBot.App.Window.ComboBox_SelectedIndexChanged(Object sender, EventArgs e) in xBot\App\Window.cs:Zeile 2426.
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   bei xBot.App.Window.InitializeValues() in xBot\App\Window.cs:Zeile 103.
   bei xBot.App.Window..ctor() in xBot\App\Window.cs:Zeile 46.
   bei xBot.App.Window.get_Get() in xBot\App\Window.cs:Zeile 56.
   bei xBot.Program.Main() in xBot\Program.cs:Zeile 16.
Das Programm "[18228] xBot.exe" wurde mit Code 0 (0x0) beendet.
```

How do you export it as .exe/setup? Or how do you even run it? I guess that there are still some references missing (Font Awesome seems to be used, but I can't see any icons in the Window.cs Forms Designer)?!

**Comment by JellyBitz** [comment]
Fixed. You may find some bug but I'm not updating xBot on WinForms anymore.

The project it's a "ready to build" but the package references, since they are local path stuffs (or it's just the .vs folder) ...

You can find Font Awesome fonts on resources, it is registered to memory on loading.
That's why you cannot check it from designer ;)

**Comment by Paragrimm** [comment]
Hey, thanks a lot, it works now :).
I need to dive more into C#/.NET myself :D. I'm coming from the frontend/JS world, otherwise I maybe could've fixed that myself.

Thanks a lot!
