### ISSUE TITLE
xBotLoader doesnt work.

### ISSUE THREAD

**Issue by turkerdev** [JellyBitz/xBot-WinForms#2]
xBotLoader doesnt work on main pc, but if i try it on virtual machine it works great.
on main pc some popup appears ' user account control ' on virtual machine it doesnt.

**Comment by JellyBitz** [comment]
UAC is Windows related, try with admin privileges.

Try this with xBot.exe and xBotLoader.exe:
> Right click > compatibility > execute as administrator.

**Comment by turkerdev** [comment]
it worked whenever i execute xBot.exe as administrator. Thanks.
