### ISSUE TITLE
building error 'JObject' does not contain a definition for 'ContainsKey' 

### ISSUE THREAD

**Issue by nagyzekkyandras** [JellyBitz/xBot-WinForms#3]
**Hello!**

While is try to build your application Im facing this issue:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1061	'JObject' does not contain a definition for 'ContainsKey' and no accessible extension method 'ContainsKey' accepting a first argument of type 'JObject' could be found (are you missing a using directive or an assembly reference?)	xBot	xBot-WinForms\xBot\App\Settings.cs	140	Active

Have you any Idea what can be wrong?

Steps to reproduce:
- clone the repository
- Install-Package System.Data.SQLite -Version 1.0.113.7
- add references from xBot-WinForms\xBot\bin\Release folder

**Comment by JellyBitz** [comment]
I didn't experienced such issue following your steps.
And it has something to do with Newtonsoft JSON actually. Probably a newer/older version which not contains ContainsKey method.

Just try the next steps:
1. Clone repository
2. Make sure to add DLL references from folder, you don't need to install anything:
 - AutoUpdater.NET
 - DevIL.NET2 (But keep DevIL into executable folder)
 - Newtonsoft.Json
 - System.Data.SQLite (But keep SQLite.Interop into executable folder)
3. Compile it.

**Comment by nagyzekkyandras** [comment]
When I open the SLN file the VS17 add a Newtonsoft.Json version by default.
I deleted and added as a reference.
Now I was able to build and publish the application.

There is any tutorial how to setup the bot for a server to test the application?
When I try to add a Media.pk file for server setup it says:
```
[06:46:58] Pk2 Extractor v1.2.0 - Made by JellyBitz
[06:47:00] Opening Pk2 file using default blowfish key
[06:47:01] Pk2 file opened!
[06:47:01] Extracting Silkroad Version
[06:47:01] Extracting Locale & Gateway
[06:47:01] Extracting Gateport
[06:47:01] Creating Database...
[06:47:01] Database has been created!
[06:47:01] Database connection error!
[06:47:01] Error
```

**Comment by JellyBitz** [comment]
> 2. Make sure to add DLL references from folder, you don't need to install anything:
> - AutoUpdater.NET
> - DevIL.NET2 (But keep DevIL into executable folder)
> - Newtonsoft.Json
> - System.Data.SQLite (***But keep SQLite.Interop into executable folder***)

Just try to follow the steps above.
